### ISSUE TITLE
Update test in gruntfile and travis

### ISSUE THREAD

**Issue by iblancasa** [angrykoala/maelstrom#157]
I am not sure if is correct:
now you have your services in different repos. Now, you have to test and deploy your services independently so, you don't have to test submodules here.

I did not make you a pull request because I am not sure if you want to do something different

**Comment by demiurgosoft** [comment]
yeah, all grunt stuff here is just legacy (cool way to say i don't want to throw it yet), eventually this will only be used to deploy and test the full server
